app:
    build: .
    volumes:
      - .:/var/www/flaskapp    
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    expose:
      - "8000"
    command: ["gunicorn", "-b", ":8000", "-w", "1", "app:app"]

nginx:
    build: .
    dockerfile: Dockerfile.nginx
    links:
        - app
    ports:
        - "80:80"

db:
    build: ../
    dockerfile: db/Dockerfile
    ports:
        - "3306:3306"
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: Adminpassword123
        MYSQL_DATABASE: employeeusers
        MYSQL_ROOT_PASSWORD: Adminpassword123